taco:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10

#logging:
#  level:
#    org.springframework.data.rest: debug

spring:
  security:
    user:
      name: buzz
      password: infinity
  data:
    rest:
      base-path: /api
  jms:
    template:
      default-destination: tacocloud.order.queue
  artemis:
    host: localhost
    port: 61616
    user: artemis
    password: simetraehcapa
    embedded:
      enabled: false

---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

  artemis:
    host: localhost
    port: 61616
    user: artemis
    password: simetraehcapa
    embedded:
      enabled: false

logging:
  level:
    tacos: WARN
    
